name: Demo action
on: [push, pull_request]
jobs:
  Siddharth-Job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello Siddharth"

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
          files: |
            **/*.php

    - name: Echo if PR contains PHP file changed
      if: steps.changed-files.outputs.any_changed == 'true'
      run: echo "PR contains a PHP file"
