name: Demo action
on: [pull_request]
jobs:
  Siddharth-Job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello Siddharth"

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2

    - id: changed-files
      uses: tj-actions/changed-files@v32
      with:
          files: |
            **/*.php

    - name: Run PHPCS
      run: composer i && ./vendor/bin/phpcs --standard=WordPress-Core ${{ steps.changed-files.outputs.all_changed_files }}

