name: Demo action
on: [pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.output1 == 'bye'
    steps:
      - run: echo ${{needs.job1.outputs.output1}}


