name: Demo action
on: [push, pull_request]
jobs:
  Siddharth-Job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello Siddharth"

    - uses: actions/checkout@v3

    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
