name: Demo action
on: [push]
jobs:
  Siddharth-Job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show contents of the current directory
      run: |
       pwd
       ls

    - name: Say goodbye
      run: echo 'Goodbye fellas!'


  Kaavya-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Show current path
      run: pwd

    - name: Print status
      run: echo "Kaavya's Job is completed"

    - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

    - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

